
inst_brew ruby
inst_brew homebrew/completions/ruby-completion
inst_brew homebrew/completions/rake-completion
inst_brew homebrew/completions/gem-completion
inst_brew git-sh
inst_brew node
inst_brew reattach-to-user-namespace
inst_brew ssh-copy-id
inst_brew terminal-notifier
inst_brew wget
inst_brew nmap
inst_brew xmlstarlet
inst_brew colordiff
inst_brew subversion
inst_brew trash
inst_brew shellcheck
inst_cask dash
inst_cask dashlane
inst_cask iphoney
inst_gem bundler
inst_gem terminal-notifier
